export const CREATE_INCOME = "CREATE_INCOME"; //POST
export const RETRIEVE_INCOME = "RETRIEVE_INCOME"; //GET
//GET by id
export const UPDATE_INCOME = "UPDATE_INCOME"; //PUT
export const DELETE_INCOME = "DELETE_INCOME"; //DELETE by id
//export const DELETE_ALL_INCOME = "DELETE_ALL_INCOME"; //DELETE
